### PR TITLE
fix: Attempt to fix Verify Namespace Owner Action should accept a blocklist #35

### LINKED ISSUE #35: Verify Namespace Owner Action should accept a blocklist
The [Verify Namespace Owner Action](https://github.com/buildpacks/github-actions#verify-namespace-owner-action) should accept a `blocklist` array of namespaces names to disallow. This would be used when `add-if-missing` is set to `true`.

This would likely be implemented as a new field on the [`config` struct in `verify_namespace_owner.go`](https://github.com/buildpacks/github-actions/blob/main/registry/verify-namespace-owner/verify_namespace_owner.go#L68), and then validated in the same way as [`AddIfMissing` in that file](https://github.com/buildpacks/github-actions/blob/main/registry/verify-namespace-owner/verify_namespace_owner.go#L117)

I'm not sure how Github passes arrays as params, so it might be best for this action to accept a comma delimited string (commas are not allowed in namespaces, so it's an acceptable delimiter)

### PR DESCRIPTION
**Pull request by mritunjaysharma394**
This PR is the first attempt to fix #35. 
## What it does till now
* Changed the internals to accept a list of strings in `registry/verify-namespace-owner/verify_namespace_owner.go`
* Modifies the `config` struct in `registry/verify-namespace-owner/verify_namespace_owner.go` to accept a list of namespaces.

## Suggestions and Feedback required
* Do we have to create another function `getListNamespaces` similar to [getNamespace](https://github.com/buildpacks/github-actions/blob/3c4c882a04b7948fbc5937b46cb37562e035671a/registry/verify-namespace-owner/verify_namespace_owner.go#L111) to check `AddIfMissing` bool or we can do it in the existing function?
* Review of the commits till now - are they in line with what we intend to do? 

Thanks!

### CODE REVIEW

File: registry/verify-namespace-owner/verify_namespace_owner.go [hunk 1]
```diff
@@ -99,6 +100,11 @@ func parseConfig(tk toolkit.Toolkit) (config, error) {
 		return config{}, toolkit.FailedError("namespace must be set")
 	}
 
+	c.ListNamespaces, ok = tk.GetInputList([]string{"list-of-namespaces"})
```
Comment (jkutner) [inline registry/verify-namespace-owner/verify_namespace_owner.go:103]: Let's renamed this to `blocked-namespaces`

File: registry/verify-namespace-owner/verify_namespace_owner.go [hunk 2]
```diff
@@ -99,6 +100,11 @@ func parseConfig(tk toolkit.Toolkit) (config, error) {
...
+	if !ok {
+		return config{}, toolkit.FailedError("namespace must be set")
```
Comment (jkutner) [inline registry/verify-namespace-owner/verify_namespace_owner.go:105]: Instead of returning an error, I think we'll want to set a default list of blocked-namespaces. In fact, we will want to append those defaults to any list provided as input too.

File: internal/toolkit/toolkit.go [hunk 3]
```diff
@@ -145,6 +146,17 @@ func (d *DefaultToolkit) GetInput(name string) (string, bool) {
 	return s, ok
 }
 
+func (d *DefaultToolkit) GetInputList(name []string) ([]string, bool) {
+	d.once.Do(d.init)
+	var ok bool
+	for _, str := range name {
+		s, ok := d.Environment[fmt.Sprintf("INPUT_%s", strings.ToUpper(str))]
```
Comment (jkutner) [inline internal/toolkit/toolkit.go:153]: I think instead of iterating over a list of `name`s, you'll need to parse the list from a single env var. We may want to define the `blocked-namespaces` as a comma separated list.

File: registry/verify-namespace-owner/verify_namespace_owner.go (hunk 1 above)
Comment (mritunjaysharma394) [reply registry/verify-namespace-owner/verify_namespace_owner.go]: In the latest commit, I have tried to change this `blockedNamespaces`, should it work?

Comment (jkutner) [reply registry/verify-namespace-owner/verify_namespace_owner.go]: yea, but I think you'll also want to change the `"list-of-namespaces"` to `"blocked-namespaces"`

Comment (mritunjaysharma394) [reply registry/verify-namespace-owner/verify_namespace_owner.go]: Oh, my bad, understood, will change that

Comment (mritunjaysharma394) [reply registry/verify-namespace-owner/verify_namespace_owner.go]: Done that, thanks a lot!

**Comment by jkutner** [comment]
@mritunjaysharma394 You'll need to [DCO signoff](https://github.com/buildpacks/github-actions/pull/44/checks?check_run_id=2578311063) your commits. This is a pain, but it's required by the CNCF. It might be easiest to squash your commits in this PR into a single commit and do signoff for just that one. I think [this guide](https://gitbetter.substack.com/p/how-to-squash-git-commits) will help explain.

File: internal/toolkit/toolkit.go (hunk 3 above)
Comment (mritunjaysharma394) [reply internal/toolkit/toolkit.go]: Hi @jkutner , have tried to fix it, please feel free to have a look, thanks

File: internal/toolkit/toolkit.go [hunk 4]
```diff
@@ -145,6 +146,13 @@ func (d *DefaultToolkit) GetInput(name string) (string, bool) {
 	return s, ok
 }
 
+func (d *DefaultToolkit) GetInputList(name string) ([]string, bool) {
+	d.once.Do(d.init)
+	s, ok := d.Environment[fmt.Sprintf("INPUT_BLOCKED_NAMESPACES_%s", strings.ToUpper(name))]
```
Comment (jkutner) [inline internal/toolkit/toolkit.go:151]:
```suggestion
	s, ok := d.Environment[fmt.Sprintf("INPUT_%s", strings.ToUpper(name))]
```

This should be `"INPUT_%s" like `GetInput`

File: registry/verify-namespace-owner/verify_namespace_owner.go [hunk 5]
```diff
@@ -47,6 +47,10 @@ func VerifyNamespaceOwner(tk toolkit.Toolkit, organizations services.Organizatio
 		return err
 	}
 
+	if isBlockedNamespaces(config{}) {
+		return toolkit.FailedErrorf("a blocked namespace encountered %s", c.Namespace)
```
Comment (jkutner) [inline registry/verify-namespace-owner/verify_namespace_owner.go:51]:
```suggestion
		return toolkit.FailedErrorf("The namespace '%s' is restricted.", c.Namespace)
```

File: internal/toolkit/mock_toolkit.go [hunk 6]
```diff
@@ -1,4 +1,4 @@
-// Code generated by mockery v2.4.0-beta. DO NOT EDIT.
+// Code generated by mockery v0.0.0-dev. DO NOT EDIT.
```
Comment (jkutner) [inline internal/toolkit/mock_toolkit.go:1]: hmm, not sure why this happened. Maybe just revert it

Comment (mritunjaysharma394) [reply internal/toolkit/mock_toolkit.go:1]: Hi @jkutner , I guess this is happening because I installed `mockery` using `go get` rather than `brew` and that's why I have the development version of it. 
Related issue: https://github.com/vektra/mockery/issues/362

However, I tried to install `mockery` using brew and then the code generated has correct version but since it installs latest version of `mockery`, that is, `v2.9.0`, I am not sure if I should use that? Or do you suggest to just simply edit it to `v2.4.0-beta`?  Thanks

File: registry/verify-namespace-owner/verify_namespace_owner.go (hunk 5 above)
Comment (mritunjaysharma394) [reply registry/verify-namespace-owner/verify_namespace_owner.go]: Thanks, I have fixed it

File: internal/toolkit/mock_toolkit.go (hunk 6 above)
Comment (jkutner) [reply internal/toolkit/mock_toolkit.go:1]: I'm not sure. Did you run `go get` (without options) from the root of the github-actions repo?

Comment (mritunjaysharma394) [reply internal/toolkit/mock_toolkit.go:1]: Nope, I installed from the instructions here: https://github.com/vektra/mockery#go-get

This was the command: `go get github.com/vektra/mockery/v2/.../` and this version mismatch is a known issue in `mockery`. Also found here: https://github.com/vektra/mockery/issues/381

Comment (mritunjaysharma394) [reply internal/toolkit/mock_toolkit.go:1]: I removed the binary installed using `go get` method and re installed `mockery` using brew. It is not showing the correct version but the version is `v2.9.0` in this case.

Comment (aemengo) [reply internal/toolkit/mock_toolkit.go]: Most likely, this version number is set at compile time. Which is what `vetktra/mockery` is likely doing for their official releases using `brew`.

`go get ...`, which fetches and builds the tool, won't be smart enough to know what version number to set.

https://github.com/vektra/mockery/blob/master/pkg/config/config.go#L3-L4

Comment (mritunjaysharma394) [reply internal/toolkit/mock_toolkit.go]: I guess you are right, the version is hardcoded it seems, @aemengo. However, I have fixed it somehow by locally installing `mockery` with its pre-built binary of the version `v2.4.0-beta` we are using. Here's a link to that: https://github.com/vektra/mockery/releases/tag/v2.4.0-beta

File: internal/toolkit/toolkit_test.go [hunk 7]
```diff
@@ -126,6 +126,17 @@ func TestToolkit(t *testing.T) {
 				Expect(ok).To(BeFalse())
 			})
 
+			it("gets input list", func() {
+				tk.Environment = map[string]string{"INPUT_BLOCKED_NAMESPACES_TEST-1": "test-value-1,test-value-2,test-value-3"}
+
+				s, ok := tk.GetInputList("test-1")
```
Comment (jkutner) [inline internal/toolkit/toolkit_test.go:132]: I don't think this should pass. Shouldn't it be `tk.GetInputList("blocked-namespaces-test-1")`?

File: registry/verify-namespace-owner/verify_namespace_owner_test.go [hunk 8]
```diff
@@ -72,13 +72,21 @@ func TestVerifyNamespaceOwner(t *testing.T) {
...
 			it("fails if add-if-missing is false", func() {
 				tk.On("GetInput", "add-if-missing").Return("", false)
+				tk.On("GetInputList", "blocked_namespaces").Return([]string{""}, false)
+				Expect(owner.VerifyNamespaceOwner(tk, o, r, s)).
+					To(MatchError("::error ::invalid namespace test-namespace"))
+			})
 
+			it("fails if namespace is blocked", func() {
+				tk.On("GetInput", "add-if-missing").Return("", false)
+				tk.On("GetInputList", "blocked_namespaces").Return([]string{""}, false)
```
Comment (jkutner) [inline registry/verify-namespace-owner/verify_namespace_owner_test.go:82]: I think this needs to return a list that includes the namespace used in the test. so:

 `.Return([]string{"test-owner"},`

Comment (mritunjaysharma394) [reply registry/verify-namespace-owner/verify_namespace_owner_test.go]: thanks a lot, @jkutner , have tried to fix it in the next commit, thanks

File: internal/toolkit/toolkit_test.go (hunk 7 above)
Comment (mritunjaysharma394) [reply internal/toolkit/toolkit_test.go:132]: I guess, it was passing, however, I will check again and revert?

Comment (mritunjaysharma394) [reply internal/toolkit/toolkit_test.go]: Yes, my bad, just fixed it, the tests are passing now

**Review by jkutner — APPROVED** [review]
